/**
	Generated by sails-inverse-model
	Date:Mon Apr 06 2020 22:45:16 GMT+0200 (GMT+02:00)
*/

module.exports = {
    attributes: {
        idCreneaux: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        heureDebut: {
            type: "string",
            columnType: "time"
        },
        heureFin: {
            type: "string",
            columnType: "time"
        },
        date: {
            type: "string",
            columnType: "date"
        },
        recurrent: {
            type: "number",
            columnType: "int",
            isInteger: true
        },
        denomination: {
            type: "string",
            columnType: "varchar",
            maxLength: 45
        },
        Type: {
            model: "Type",
            required: true
        }
    }
};