/**
	Generated by sails-inverse-model
	Date:Mon Apr 06 2020 22:45:16 GMT+0200 (GMT+02:00)
*/

module.exports = {
    attributes: {
        idEnfant: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        nom: {
            type: "string",
            columnType: "varchar",
            maxLength: 45
        },
        prenom: {
            type: "string",
            columnType: "varchar",
            maxLength: 45
        },
        age: {
            type: "number",
            columnType: "int",
            isInteger: true
        },
        aille: {
            type: "number",
            columnType: "decimal"
        },
        poid: {
            type: "number",
            columnType: "decimal"
        },
        Parent: {
            model: "utilisateur",
            required: true
        },
        Creneaux_Creneaux: {
            model: "Creneaux",
            required: true
        }
    }
};