/**
	Generated by sails-inverse-model
	Date:Mon Apr 06 2020 22:45:16 GMT+0200 (GMT+02:00)
*/

module.exports = {
    attributes: {
        idRetour: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        heure: {
            type: "number",
            columnType: "int",
            isInteger: true
        },
        date: {
            type: "string",
            columnType: "date"
        },
        depassement: {
            type: "number",
            columnType: "int",
            isInteger: true
        },
        Creneaux: {
            model: "Creneaux",
            required: true
        },
        Type: {
            model: "Type",
            required: true
        },
        Mesure: {
            model: "Mesure",
            required: true
        }
    }
};