/**
	Generated by sails-inverse-model
	Date:Mon Apr 06 2020 22:45:16 GMT+0200 (GMT+02:00)
*/

module.exports = {
    attributes: {
        idType: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        intensite: {
            type: "number",
            columnType: "int",
            isInteger: true
        },
        seuil: {
            type: "number",
            columnType: "int",
            isInteger: true
        }
    }
};