/**
	Generated by sails-inverse-model
	Date:Mon Apr 06 2020 22:45:16 GMT+0200 (GMT+02:00)
*/

module.exports = {
    attributes: {
        idutilisateur: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        nom: {
            type: "string",
            columnType: "varchar",
            maxLength: 45
        },
        prenom: {
            type: "string",
            columnType: "varchar",
            maxLength: 45
        }
    }
};